### ISSUE TITLE
ConTabs table output oneliner?

### ISSUE THREAD

**Issue by tdwright** [tdwright/contabs#36]
Sometimes we want to spit out a table ASAP and are happy with all the default options.

We'd want to do something like:

```C#
Console.WriteLine(Table<Planet>.QuickString(planets));
```

**Comment by dswaczyna** [comment]
Hello tdwright,

I would like to clarify changes pointed in this issue.
I wonder if I understood it correctly but you request to add function that can just print content of a table?
so instead of:
```
var table = Table<Planet>.Create(Planets);
Console.WriteLine(table.ToString());    
```
should be possibility to write:
`Console.WriteLine(Table<Planet>.QuickString(planets));`

but u could already write it as: 
`Console.WriteLine(Table<Planet>.Create(planets));`

So it wouldn't be the some kind of code duplication?

**Comment by tdwright** [comment]
That's true @dswaczyna - good point.

I wonder whether there's any value in condensing it even further, from:

```C#
Console.WriteLine(Table<Planet>.QuickDraw(planets));
```
To:
```C#
Table<Planet>.QuickDraw(planets);
```
Or should we just close this issue and move on? 😉

**Comment by dswaczyna** [comment]
@tdwright 
to be honest, I'm not sure, it's my very first activity on github.

Surely, it does not require a lot of work to implement QuickDraw function so it could be done but from the other hand, it could be a little bit misleading at the same time.
because when there is:

`Table<Planet>.QuickDraw(planets);`

shouldn't be also a possibility to invoke Draw() function with style parameters?
`Table<Planet>.Draw(planets, Style.Heavy);`

These are just my thoughts, at the end, you are the owner so need to decide 😉

**Comment by tdwright** [comment]
Hi @dswaczyna,

I think the direction you're heading in with that suggestion is quite close to what @rahl0b10 was suggesting in #20. I.e. a builder pattern that allows things like styles to be defined in a fluent style.

On reflection, I'm going to close this issue. Please don't be dissuaded from contributing though! 😀 

Tom
